#!/bin/bash
if [ -z "$1" ]; then echo "\
lst <filename> [...<filename>]
  output (stat):
filename/size-in-bytes/last-modified-timestamp\
"; fi

for filename in "$@"; do
	stat --format="%n/%s/%Y" "$filename"
done
