#!/bin/bash

# depends on streect

SEP='  '

# only first arg to process
[ -z "$1" ] && ARG="."
ARG=$(dirname "$1")
[ -d "$1" ] && cd "$1"

###############
# MAIN
###############

	# streect:
	#find "$ARG" -mindepth 1 | cut -c 3- \
	#| LC_ALL=C sort \

__md5=$(\
	streect \
	| tr -cd '/\n'  | awk '{ print length }' \
	| tr '\n' , \
	| sed 's/^\(.*\).$/\1./' \
	| md5sum -b | cut -c-32
)
echo -n "$__md5$SEP" 
basename "$(pwd)" 

