#!/bin/bash

# check if hashes in all files *.md5 are in directory's .md5
# throw error message on that is not

for fn in ?*.md5; do 
	__md5=$(cat $fn)
	grep $__md5 .md5 1>/dev/null \
	|| echo "ERROR: $fn: $__md5" >2
done
