#!/bin/bash

# converts file strings from .olr(s) to .tar.md5l (was tar_md5list)
# grep is the same as in olr-files
# input as args or stdin
SEP_OLR='  '

[ -z "$1" ] && [[ -p /dev/stdin ]] && set -- '-'

cat "$@" \
	| grep -aP '\[[\da-fA-F]{32}\.\d+\][^]]*$' \
	| perl -pe 's/^(.+)'"$SEP_OLR"'\[([\da-f]{32}).\d+\][^]]*$/$2  $1\n/'

