#!/bin/bash
x="$(PS1="$PS1" echo -n | bash --norc -i 2>&1)"; echo -n "${x%exit}"

# # http://stackoverflow.com/questions/3451993/echo-expanded-ps1
# # http://stackoverflow.com/a/24006864
# # x="$(PS1="$PS1" echo -n | bash --norc -i 2>&1)"; echo "‘${x%exit}’"
# x="$(PS1="$PS1" echo -n | bash --norc -i 2>&1)"; echo -n "${x%exit}"
# # x="$(PS1="$PS1" echo -n | bash --norc -i 2>&1 > /dev/null)"; echo "‘${x%exit}’"
# x="$(PS1="$PS1" echo -n | bash --norc -i 2>&1 > /dev/null)"; echo -n "${x%exit}"
