#!/bin/bash
# command name: trash-rm
shopt -s extglob
recursive=1
declare -a cmd
((i = 0))
for f in "$@"
do
  case "$f" in
    (-*([fiIv])r*([fiIv])|-*([fiIv])R*([fiIv]))
    tmp="${f//[rR]/}"
    if [ -n "$tmp" ]
    then
      #echo "\$tmp == $tmp"
      cmd[$i]="$tmp"
      ((i++))
    fi
    recursive=0 ;;
    (--recursive) recursive=0 ;;
    (*)
    if [ $recursive != 0   -a  -d "$f" ]
    then
      echo "skipping directory: $f"
      continue
    else
      cmd[$i]="$f"
      ((i++))
    fi ;;
  esac
done
#Update: starting with Ubuntu 12.04 Precise Pangolin, trash-cli provides the command "trash-put" to trash files, instead of the previous "trash" command, so in the code above, on the last line, replace "trash" with "trash-put" for Ubuntu 12.04+.

#trash "${cmd[@]}"
trash-put "${cmd[@]}"

