#!/bin/bash

MAC=00-19-d1-01-b7-55
Broadcast=192.168.1.255
PortNumber=9

# The WOL magic packet is composed of 
# ffffffffffff (12 times f) 
# followed by 16 times the destination MAC without colons (:).

# The sed command is used here to remove colons (:) from the MAC 
# and to add the \x hex specificator.

echo -e $(echo $(printf 'f%.0s' {1..12}; printf "$(echo $MAC | sed 's/-//g')%.0s" {1..16}) | sed -e 's/../\\x&/g') \
| nc -w1 -u $Broadcast $PortNumber
#| nc -w1 -u -b $Broadcast $PortNumber

# CygWin's NetCat version doesn't need for -b parameter.

